### ISSUE TITLE
Make CI plot have fixed axes

### ISSUE THREAD

**Issue by jzelner** [epibayes/epitutorials#4]
Right now, the limits on this plot change w/the number of samples: 
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/136323/180007047-f5d141c5-2965-4c9f-9925-b757efc996f4.png">

We want the y-axis to be fixed and to see the CIs grow or shrink based on the underlying variation in the variable of interest and the total number of samples. Thankfully, this should be easy to fix by setting the limits on the axis to mean +/- 70 or so.

**Comment by choisteph** [comment]
right now `ymin` and `ymax` are `lowCI` (`round(mean(x2()) - sse(), 2)`) and `highCI` (`round(mean(x2()) + sse(), 2)`). Are you saying `ymin` and `ymax` should instead be `mean-70` and `mean+70`? In that case what do I do with `lowCI` and `highCI`?

**Comment by jzelner** [comment]
The `ymin` and `ymax` are fine, but it's the limits of the figure that are the issue, i.e. `ylim`. Those should be mean +/- 70; does that make sense?

**Comment by choisteph** [comment]
I don't think you can add ylims to errorbar plots (or at least, the documentation isn't showing me you can). been trying to add ylim but getting an error.

**Comment by jzelner** [comment]
It's a plot-level thing:

https://ggplot2.tidyverse.org/reference/lims.html

**Comment by choisteph** [comment]
might have gotten it to work.[ please check this commit](https://github.com/epibayes/epitutorials/commit/15da989cf0c184e491f61b97df1a227563bc1533).
